name: Collect Smart City Data

on:
  schedule:
    # Runs at the top of every hour
    - cron: '0 * * * *'
  workflow_dispatch: # Allows you to run it manually

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - run: pip install -r requirements.txt
      - name: Run data collection script
        env:
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          SUPABASE_CONNECTION_STRING: ${{ secrets.SUPABASE_CONNECTION_STRING }}
        run: python collect_data.py