name: 15-Min Data Ingestion

on:
  repository_dispatch:
    types: [trigger-ingestion]
  workflow_dispatch: # Allows you to click a button to test it manually

jobs:
  collect-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install pandas requests sqlalchemy psycopg2-binary

      - name: Run Ingestion Script
        env:
          OPENWEATHER_API_KEY: ${{ secrets.OPENWEATHER_API_KEY }}
          WAQI_TOKEN: ${{ secrets.WAQI_TOKEN }}
          SUPABASE_CONN_STR: ${{ secrets.SUPABASE_CONN_STR }}
        run: python collect_data.py
